### PR TITLE
Added request timeout

### PR DESCRIPTION
**Pull request by Zumochi**
Added request timeout of 30 seconds because of timeout spam (most requests take about 15 seconds for me (from EU), so the current 10 is on the very low side. Thus 30 seconds to be safe :wink: ).
Increased interval to check for availability from 10 to 30 seconds (have been getting some connection refused as well :disappointed: )
15 + 30 still checks more than once a minute, that's more than plenty in my opinion.

Let me know if I did it right :smile: (not 100% sure about the config).

### CODE REVIEW

**Comment by MA3STR0** [comment]
Thanks for your contribution. Good idea with request_timeout, please make it configurable in config.json with default of 20-30 sec and I will merge.
No need to include changes in default config though, it is kept minimal to help users get script running quickly. Then everyone can look up details in the readme.
Besides, there was a feedback that 10 seconds interval is not enough for KS-1 and some guys set it to 7. So no need to update defaults, keep things configurable and everyone will be happy :)

**Comment by Zumochi** [comment]
Do you mean I should keep the values out of the config, but allow the user to add the values themselves?

**Comment by MA3STR0** [comment]
Thats better, thanks.
Maybe I will update the default config later when I have more info

**Comment by Zumochi** [comment]
Cool, thanks for merging!

**Pull request merged**
